spring.application.name=demo



# Conexão com MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/baseline
spring.datasource.username=admin
spring.datasource.password=hyan01

# Dialeto do MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Atualização automática das tabelas (pode ser update, create, create-drop, validate)
spring.jpa.hibernate.ddl-auto=create

# Mostrar queries no console
spring.jpa.show-sql=true
